### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by james-w-roach** [jamesroach7/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create the HTML page
- [x] Add the car image to an img tag in the HTML
- [x] Create a stylesheet and link it to the html file
- [x] Style the CSS to ensure the car is the right size and is placed properly
- [x] Finalize CSS
