### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by james-w-roach** [jamesroach7/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add event listener that listens for arrow keys being pressed
- [x] ensure the car rotates left or right depending on which key is pressed
- [x] add transition to css that smoothes out each turn
- [x] finalize css
