### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by james-w-roach** [jamesroach7/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add event listener for the space bar being pressed
- [x] create a function that moves car across screen
- [x] call the set interval function and set interval to 16 ms
- [x] fix errors
